version: 2

jobs:
  build:
    working_directory: ~/ring-curl

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-ring-curl-{{ checksum "project.clj" }}

      - run:
          name: build
          command: |
            ./ci/compile.sh
            mkdir target/jar
            mv target/*.jar target/jar/

      - save_cache:
          key: v1-ring-curl-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

      - run:
          name: test
          command: ./ci/test.sh

      - store_test_results:
          path: ./target/surefire-reports

      - store_artifacts:
          path: ./target/jar

      - persist_to_workspace:
          root: .
          paths:
            - ./ci/*
            - ./target/jar/*
            - ./lein.sh
            - ./project.clj

  release:
    working_directory: ~/ring-curl

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - attach_workspace:
          at: ~/ring-curl

      - run:
          name: export version
          command: ./ci/export-version.sh

      - run:
          name: move jar back to target
          command: mv target/jar/*.jar target/

      - run:
          name: create release on GitHub
          command: ./ci/release-github.sh

      - run:
          name: create release on Clojars
          command: ./ci/release-clojars.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - release:
          requires:
            - hold
